"""Common StressEar-AI variable schema."""

COMMON_SCHEMA = {
    "person_id": "unique deidentified participant identifier",
    "dataset": "KNHANES or NHANES",
    "cycle": "survey cycle or year",
    "age": "age in years",
    "sex": "sex/gender as reported",
    "employment_status": "currently employed status where available",
    "occupation_group": "harmonized occupation group where available",
    "perceived_stress": "dataset-specific perceived stress item",
    "sleep_hours": "sleep duration",
    "depression_symptoms": "depression or mood variable where available",
    "occupational_noise": "workplace loud noise exposure",
    "recreational_noise": "non-work noise exposure",
    "hearing_protection": "use of hearing protection",
    "tinnitus_status": "self-reported tinnitus presence",
    "tinnitus_bother": "tinnitus annoyance/burden where available",
    "hearing_difficulty": "self-reported hearing difficulty",
    "left_pta": "left-ear pure-tone average",
    "right_pta": "right-ear pure-tone average",
    "better_ear_pta": "minimum of left and right PTA",
    "worse_ear_pta": "maximum of left and right PTA",
    "asymmetric_loss": "difference between ears above prespecified threshold",
    "hearing_loss_pta": "binary or ordinal PTA-based hearing loss",
    "survey_weight": "analysis weight",
    "strata": "survey stratum",
    "psu": "primary sampling unit",
}
